### PR TITLE
use longer time if deadline is set

### PR DESCRIPTION
**Pull request by sivchari**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

If the context deadline is set and the time is longer than default wait time, deadline time is preferred.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
```

#### Additional documentation e.g., Usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by vladimirvivien — COMMENTED** [review]
Hi @sivchari 
Since kwok is a cluster provider, should this behavior implemented with other cluster providers like Kind?
cc @harshanarayana

**Comment by harshanarayana** [comment]
+1 to what @vladimirvivien  mentioned. Guess this can be a general thing across each providers ?

**Comment by sivchari** [comment]
Kind has --wait flag, but it's not used in cluster provider. If we'll use it, we should new parameter to wait. Should I change it ?

**Comment by vladimirvivien** [comment]
@sivchari (apologies for late reply)
How is the `Duration` value passed in to Kwok as a provider ?
We should use the same mechanism to pass it to kind if possible.
If a flag is needed, we can explore that.

**Comment by sivchari** [comment]
KWOK has already had `waitDruration` in struct. So if Kind also has wautDuration in [Cluster](https://github.com/kubernetes-sigs/e2e-framework/blob/main/support/kind/kind.go#L43-L50), we can control the duration time when to wait, can't it ?

**Comment by vladimirvivien** [comment]
@sivchari yes, but I am not sure if that is already built into kind (which would make it easier to implement).

**Pull request closed without merging**
