### PR TITLE
Dependencies update / Go upgrade to 1.22 and cleanup

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup
/kind feature

#### What this PR does / why we need it:

- Dependencies update / Go upgrade to 1.22 and cleanup

xref: https://github.com/kubernetes-sigs/e2e-framework/pull/407

need: https://github.com/kubernetes/test-infra/pull/32555

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Dependencies update / Go upgrade to 1.22 and cleanup
```

#### Additional documentation e.g., Usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by harshanarayana — COMMENTED** [review]
/lgtm

**Review by vladimirvivien — COMMENTED** [review]
/lgtm

**Comment by cpanato** [comment]
@vladimirvivien i will figure out the time out that is happening

**Comment by cpanato** [comment]
@harshanarayana @vladimirvivien now it is ready :)

**Pull request merged**
