### PR TITLE
match on exact cluster names

### PR DESCRIPTION
**Pull request by crandles**
The current implementation of how we check for cluster existence is too permissive:

https://github.com/kubernetes-sigs/e2e-framework/blob/fee1391aeccdc260069bd5e0b25c6b187c2293c4/support/kind/kind.go#L87-L90

If clusters are created using a similar prefix or using a name that happens to be a substring of another cluster, this will not work as intended.

Adjusted the function signature slightly, in the attempt to reduce code duplication. _Most_ users should be unaffected as the addition is a variadic parameter:
```go
func (k *Cluster) CreateWithConfig(imageName, kindConfigFile string) (string, error) {
	return k.Create("--image", imageName, "--config", kindConfigFile)
}

func (k *Cluster) Create(args ...string) (string, error) {
...
```

### CODE REVIEW

**Review by ShwethaKumbla — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by vladimirvivien — APPROVED** [review]
/lgtm

**Pull request merged**
