### PR TITLE
Add a envconfig.Config method to inject a client from kubeconfig file

### LINKED ISSUE #39: Provide a `envconfig.Config` method to inject a client from kubeconfig file.
The example here reveals the multi-steps necessary to create a klient.Client from a kubeconfig file and then inject that client into the environment's configuration.

https://github.com/kubernetes-sigs/e2e-framework/blob/0402e818c25b73fb4a7c896a9ac5008d3dc06a18/examples/k8s/main_test.go#L52

It would be nice if the `envconf.Config` type provided a method to handle the injection of the client in one step similar to:

```go
func TestMain(m *testing.M){
    testenv.Setup(
        func(ctx context.Context, cfg *envconf.Config) (context.Context, error) { 
            cfg.WithKubeconfigFile(kubeconf_file_path) // this would create a new klient.Client, then inject it in the cfg
        },
    )
    ...
}
```

### PR DESCRIPTION
**Pull request by tech-geek29**
This commit fixes #39

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm
/assign @vladimirvivien

**Review by vladimirvivien — APPROVED** [review]
/lgtm

**Pull request merged**
