### PR TITLE
Add exec function to run commands inside pod

### PR DESCRIPTION
**Pull request by matrus2**
Hi,

It might be useful to have possibility to execute a command inside a pod by a single build-in function during for instance network testing.  

Thanks

### CODE REVIEW

**Comment by ShwethaKumbla** [comment]
@matrus2 Could you please resolve the failed tests?

**Comment by matrus2** [comment]
/cc @vladimirvivien 
Would love to see this functionality in place. May I ask you to have a quick look?

**Comment by vladimirvivien** [comment]
@matrus2 please take a look.

**Review by vladimirvivien — COMMENTED** [review]
Hi @matrus2 when you get a chance, please take a look at my previous suggestions (add an example). Then squash the commits please. Thank you.

**Pull request closed without merging**
