### PR TITLE
Cni

### PR DESCRIPTION
**Pull request by matrus2**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

This PR demonstrates how to use Cilium as a CNI in coordination with the test framework on Kind. This combines couple of build in functionalities. The example of how to mix these three (cni, kind, e2e) might be useful for somebody to bootstrap easily.

### CODE REVIEW

**Comment by harshanarayana** [comment]
@matrus2 this is a fantastic addition to our example collection.. Thanks for adding this 

/ok-to-test

**Comment by matrus2** [comment]
One more time Kwok tests #335 
/retest

**Comment by vladimirvivien** [comment]
@matrus2 as @harshanarayana said, this is an amazing set of examples. This definitely showcases what can be done with the framework. Thanks 🎉 🎉 🎉

**Review by vladimirvivien — APPROVED** [review]
/lgtm

**Pull request merged**
