### PR TITLE
Allow custom labels and annotations for namespace creation

### LINKED ISSUE #364: Allow adding custom labels and annotations when creating namespace
### What do you want to see?

Hello :wave: 
I was wondering if we could consider allowing to add user-defined labels and annotation when creating a namespace with [envfuncs.CreateNamespace](https://github.com/kubernetes-sigs/e2e-framework/blob/v0.3.0/pkg/envfuncs/ns_funcs.go#L38).

The feature request is motivated by the fact that in our case we use custom labels and annotations to configure behaviors of the namespace like cascade deletion of the namespace even if resources still exist in it, or adding metadata related to which feature is running in the namespace.
What do you think about it?

For the implementation, I think it could be easily added with an option pattern:
```
type CreateNamespaceOpts func(ns *corev1.Namespace)

func WithLabels(client klient.Client, labels map[string]string) CreateNamespaceOpts {
  return func(ns *corev1.Namespace) {
    client.Ressources.Labels(&ns, labels)
  }
}

func WithAnnotations(client klient.Client, annotations map[string]string) CreateNamespaceOpts {
	return func(ns *corev1.Namespace) {
		client.Ressources.Annotate(&ns, annotations)
	}
}

func CreateNamespace(name string, opts ...CreateNamespaceOpts) env.Func {
	return func(ctx context.Context, cfg *envconf.Config) (context.Context, error) {
		namespace := corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: name}}
		client, err := cfg.NewClient()
		if err != nil {
			return ctx, fmt.Errorf("create namespace func: %w", err)
		}
               for _, opt := range opts {
		        opt(client, &namespace)
	       }
		if err := client.Resources().Create(ctx, &namespace); err != nil {
			return ctx, fmt.Errorf("create namespace func: %w", err)
		}
		cfg.WithNamespace(name) // set env config default namespace
		return context.WithValue(ctx, namespaceContextKey(name), namespace), nil
	}
}
```

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by Fricounet**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Create 2 new option functions that can be used when calling `CreateNamespace` to add custom labels and annotations to the namespace.

#### Which issue(s) this PR fixes:

Fixes #364 

#### Special notes for your reviewer:

I also added tests to make sure the function work as expected (this is how I discovered #381), however it looks like there is no automated testing in place. In the meantime, tests can be run with `go test ./pkg/envfuncs`.

To be merged after #381 

#### Does this PR introduce a user-facing change?

```release-note
Added a way to create namespaces with custom labels and annotations
```

#### Additional documentation e.g., Usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
/ok-to-test

**Review by vladimirvivien — COMMENTED** [review]
Thanks @Fricounet
This looks great to me.
@harshanarayana PTAL, if you are OK, please approve.

**Review by harshanarayana — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
