### PR TITLE
third_party/ko: Add ko as third party tools

### PR DESCRIPTION
**Pull request by heylongdacoder**
Add Install, BuildLocal and GetLocalImage functions.

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Already explained in #343 

#### Which issue(s) this PR fixes:

Partially addresses #343 

#### Special notes for your reviewer:

N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., Usage docs, etc.:

```docs
N/A
```

### CODE REVIEW

**Comment by heylongdacoder** [comment]
Hi @vladimirvivien, I just realized you were suggesting the BuildLocal function should build and publish to a local Docker. This PR is about ko and a KinD cluster. Since KinD is a popular way to test controllers and operators, I think this PR might be helpful. If so, maybe we can merge this PR first and then create another follow-up PR for the BuildLocal (Docker) and BuildRemote (Docker) functions. WDYT? 😄

**Review by cpanato — COMMENTED** [review]
/ok-to-test

**Comment by vladimirvivien** [comment]
@heylongdacoder this is great.
So, does this PR allow local build of images and deploy images into a running Kind cluster?

@harshanarayana cc

**Comment by cpanato** [comment]
it looks great, just one question why not use `ko` as lib instead need to have that installed and use via shell?

**Comment by vladimirvivien** [comment]
+1 on @cpanato question.

**Comment by heylongdacoder** [comment]
> does this PR allow local build of images and deploy images into a running Kind cluster?

@vladimirvivien yes, you are right 😄 

> why not use ko as lib

@cpanato @vladimirvivien , I never think about this because other tools was installed and use via shell. But if we want to use `ko` as lib, do we need to ensure `ko` maintainers agree to maintain those functions signature?

**Comment by harshanarayana** [comment]
+1 from me too.  I like the idea of integrating this as a lib instead of the CLI. 


I have been using `ko` as a lib for my work related item for a while in dev mode. They even have a doc around it. https://ko.build/advanced/go-packages/

With this in place, I suppose there is going to be some guarantee on backward compatibility.

**Comment by harshanarayana** [comment]
>  So, does this PR allow local build of images and deploy images into a running Kind cluster?

We should be able to chain the build call to the kind providers load image to get this working. Right ? @vladimirvivien

**Comment by tsl409** [comment]
+1 definitely nice to have!

**Comment by cpanato** [comment]
I think, for now, we can keep it as is. We have other tools that follow this approach.
and as a follow up, we can migrate to use as a lib

**Review by cpanato — APPROVED** [review]
/approve

/hold for @harshanarayana @vladimirvivien

**Review by harshanarayana — COMMENTED** [review]
/lgtm

**Comment by vladimirvivien** [comment]
Thanks @heylongdacoder this is great.

All good points raised here. Brining ko Go dependency could be overkill and since Kind uses OS commands, I think this is Ok as well. 

As @harshanarayana mentioned, I think it a user should be able to load the docker image in Kind. Maybe an example to show the whole cycle of build and load would be useful.

**Comment by heylongdacoder** [comment]
> Maybe an example to show the whole cycle of build and load would be useful.

https://github.com/kubernetes-sigs/e2e-framework/pull/415/files#diff-5e974e6375efb2beaa1644b28e57ba8e5c006b9dab1b47620b4edc24cd50d042R40, it is actually here. The KinD cluster is created in `main_test.go`. Then, the ko `BuildLocal` function is used to build the `testdata/example_goapp` and load it into the KinD cluster using its name. Do you all think this is good enough? 😄

**Comment by heylongdacoder** [comment]
thanks for all the review!

**Pull request merged**
