### PR TITLE
enable issue and pr templates

### LINKED ISSUE #295: Issue template
I think it would be nice to have a simple issue and feature request template to make it easier to understand and reproduce issues. I see it has to be configured `.github` folder. Example for [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/tree/master/.github/ISSUE_TEMPLATE). 

Let me know your thoughts I can take a look at it.

### PR DESCRIPTION
**Pull request by harshanarayana**
Closes #295

### CODE REVIEW

**Comment by harshanarayana** [comment]
@cpanato  @vladimirvivien  How do I quickly verify these templates look right and render properly without having to merge it first ?

**Comment by phisco** [comment]
@harshanarayana, FYI: I usually enable issues on my fork and merge them on main there

**Comment by harshanarayana** [comment]
@phisco I created a dummy repo and tested this out. 😄

**Pull request merged**
