### PR TITLE
update controller-runtime to 0.11.0 and their dependencies

### LINKED ISSUE #86: Upgrade controller-runtime to latest version
I noticed that the version of controller runtime used is [`v0.9.0`](https://github.com/kubernetes-sigs/e2e-framework/blob/main/go.mod)

Is it possible to bump this to a latter version of controller runtime? It seems that `v0.9.0` of controller runtime uses an older version of spf13/cobra which has a few security vulnerabilities (which aren't actually ever executed)

Happy to open a PR! Thanks much!

### PR DESCRIPTION
**Pull request by cpanato**
- update controller-runtime to 0.11.0 and their dependencies

Fixes #86 

/assign @vladimirvivien

### CODE REVIEW

**Comment by cpanato** [comment]
we will need to run the jobs using go 1.17

**Comment by cpanato** [comment]
job update: https://github.com/kubernetes/test-infra/pull/25104

**Comment by cpanato** [comment]
@vladimirvivien with that should we bump the go module to 1.17 or is okay to keep in 1.16?

**Comment by cpanato** [comment]
@vladimirvivien done, PTAL

**Review by vladimirvivien — APPROVED** [review]
LGTM

**Pull request merged**
