### PR TITLE
Fix timeout with context for wait

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

``` golang
err = wait.For(
	func(ctx context.Context) (done bool, err error) {
		...
	},
	wait.WithContext(ctx),
	wait.WithTimeout(600*time.Second),
)
```

The timeout is ignored when both context and timeout are specified

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., Usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by wzshiming** [comment]
Done, sorry for late to reply, miss in notification.

**Comment by wzshiming** [comment]
/cc @vladimirvivien
/cc @harshanarayana

PTAL

**Review by vladimirvivien — COMMENTED** [review]
This looks pretty good. Thank you.
/lgtm

**Comment by vladimirvivien** [comment]
cc @harshanarayana please take a second look.

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by harshanarayana — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
