### PR TITLE
Fix DeleteNamespace not retrieving ns from ctx

### PR DESCRIPTION
**Pull request by Fricounet**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The function DeleteNamespace was not succeeding in retrieving the namespace from the context because it tried to cast a corev1.Namespace to *corev1.Namespace.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
```

#### Additional documentation e.g., Usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
/lgtm

/assign @harshanarayana

**Review by vladimirvivien — COMMENTED** [review]
Again, thanks @Fricounet .
Is there a test for that delete case?  If not, can you add one?  Thank you.

**Comment by Fricounet** [comment]
@vladimirvivien there were no tests for the delete. If that is fine with you (and because it will be a mess to refactor the 2 PRs otherwise), I've created a [test](https://github.com/kubernetes-sigs/e2e-framework/pull/382/commits/9f3b76f9d5168d8161d38e9200ec91966637245c) for `DeleteNamespace` in the other PR I opened (#382). Is that ok for you?

**Comment by vladimirvivien** [comment]
Yes that is ok. I just want to use opportunity to add a test to avoid a future bug. Thanks again .

**Pull request merged**
